services:
  - type: web
    name: moc-chau-ai-api
    env: python
    buildCommand: "pip install -r requirements.txt && python train.py"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
